### ISSUE TITLE
Tests failing for fedora 24+

### ISSUE THREAD

**Issue by kwizart** [NVIDIA/libglvnd#93] opened 2016-08-30 16:58 UTC
Theses tests have failed in fedora 24 using the following command:

FAIL: testglxqueryversion.sh
FAIL: testglxnscrthreads.sh

xvfb-run -a  make check V=1 

We are using the xvfb server as recommanded by the fedora packaging guideline in order to have an Xorg server under a chrooted build environnement : https://fedoraproject.org/wiki/PackageMaintainers/GraphicalTests

**Comment by nwnk** [comment] 2016-08-30 17:30
F24 doesn't support GLX_EXT_libglvnd yet so that's not entirely surprising.

**Comment by kbrenneman** [comment] 2016-08-30 17:36
In this case, the problem is simply that testglxqueryversion and testglxnscrthreads are broken and haven't been fixed yet.

The other unit tests don't actually depend on GLX_EXT_libglvnd at the moment. They all set the environment variable to override the vendor library selection.

In addition, Xvfb doesn't support GLX at all, so anything that actually requires GLX isn't going to work.

**Comment by kwizart** [comment] 2016-08-30 17:41
Ok as I understand, you might plan to update theses tests ?
May I suggest that the test doesn't fail if using Xvfb, but instead are mentioned as "can't test" ?

@nwnk is there any plan to backport this support or is it only scheduled for xorg-server 1.19 ?

**Comment by kbrenneman** [comment] 2016-08-30 18:19
> Ok as I understand, you might plan to update theses tests ?
> May I suggest that the test doesn't fail if using Xvfb, but instead are mentioned as "can't test" ?

I do plan to update them, I just haven't gotten to it yet. But when I do, I'll see if I can get it to check for the GLX and GLX_EXT_libglvnd extensions at runtime so that it skips the tests instead of failing.

**Comment by kbrenneman** [comment] 2016-10-29 01:35
Okay, I've removed the testglxnscrthreads test entirely, since it depends on x11glvnd, and I updated the testglxqueryversion test so that it'll report itself as skipped instead of failed if the server doesn't support GLX.

**Comment by kbrenneman** [comment] 2016-10-31 22:22
Okay, the last of the x11glvnd-related stuff is removed, so I'll close this bug.

**Closed by kbrenneman** 2016-10-31 22:22 UTC
