### ISSUE TITLE
libEGL_nvidia.so.0 is loaded unconditionally when installed

### ISSUE THREAD

**Issue by kwizart** [NVIDIA/libglvnd#121] opened 2017-05-30 15:29 UTC
When installing the nvidia driver the 10_nvidia.json file is installed into /usr/share/glvnd/egl_vendor.d.
So it's before the 50_mesa.json file that overrides the load of the mesa version.

This is fine when the nvidia driver is meant to be used, but if the driver isn't used for any reason (nvidia.ko failed to load or else) and the nouveau driver is used as a fallback, then eglinfo fails because the libEGL_nvididia is used instead of the mesa version.

**Comment by kbrenneman** [comment] 2017-05-30 15:42
@kwizart - Do you mean that an eglGetDisplay or eglGetPlatformDisplay call ends up trying to use the NVIDIA driver, or just that the driver is loaded at all?

**Comment by kwizart** [comment] 2017-05-30 16:31
Well, I can reproduce the other way (loading mesa instead of libEGL_nvidia.so.0 when nvidia driver is used) , with vlc (so it's not only eglinfo).

Using vlc -V gl -vv 'video_stream. on a desktop with nvidia driver installed and loaded.
If using 10_nvidia.json I have:

> ...
> egl_x11 gl debug: EGL version 1.4 by NVIDIA
> ...

But if moving the file from 10_nvidia.json to 90_nvidia.json

> ...
> egl_x11 gl debug: EGL version 1.4 (DRI2) by Mesa Project
> ...

So despite both files are presents, there is no runtime test to known which EGL backend should be used.  Things seem to be hardcoded in a way or another.

**Comment by kbrenneman** [comment] 2017-05-31 18:46
GLVND's vendor library selection works by calling an eglGetPlatformDisplay-like function for each vendor library, in order. It stops when it finds the first vendor that returns something other than EGL_NO_DISPLAY. After that, any EGL functions that use that display handle will get dispatched to whichever vendor library returned it.

The intent was that each vendor library would check to see whether it could actually do anything with the display before returning a valid EGLDisplay handle. But, it looks like both the NVIDIA driver and Mesa leave any such validation for eglInitialize.

The closest thing that GLVND could do would be to call the vendor's eglInitialize and eglTerminate functions to check whether a display is valid. But, a vendor library could likely be much more efficient about it than going through an entire redundant eglInitialize/eglTerminate sequence. And even if the vendor library doesn't have anything more efficient to do, then it can still call its own eglInitialize just as easily as GLVND could.

**Comment by kwizart** [comment] 2017-06-01 07:18
I don't know if it really worth for Mesa to check the display at the eglGetPlatformDisplay step ?

The reason is that Mesa is probably more resilient to error or miss configuration than NVIDIA, or even any others "vendor specifics drivers", and can probably work as a fallback in many situations.
Even In the case of missing nouveau kernel module the Mesa driver might still be able to recover using softpipe emulation.
Also, in the event of a failing Mesa, I'm not sure which driver will be able to recover ?
This means :
- Mesa had to be tried last (maybe moving from 50_mesa.json to 90_mesa_json) ?
- Mesa should be able to always succeed (to some degree), so it can work in a fallback situation if no better driver is able to handle the display.

**Comment by cubanismo** [comment] 2017-06-01 16:04
I think it's reasonable for Mesa to attempt to determine whether it owns the server side of the native display provided though.  At present, it seems unlikely a Mesa EGL client is going to succeed in rendering to an NVIDIA X screen, for example.

**Comment by kbrenneman** [comment] 2017-06-01 16:32
If Mesa's software renderer can run on whatever display you care to point it at, then I think it would make sense to put it late in the ordering as a fallback.

Of course, if both the vendor-specific driver and Mesa failed, then EGL simply won't work at all, and there's really nothing that GLVND could do about it.

**Comment by kwizart** [comment] 2017-06-05 12:31
I wonder if the same issue occurs in the vulkan icd loader case.
As vulkainfo shows:
Xlib: extension NV-GLX missing on display ":0".

I think the nvidia_icd.json is probably discarded as appropriate here. (Using intel under wayland on optimus setup where the nvidia driver remains installed). But it might be a side effect as GLX shouldn't have been used at all under wayland (unless vulkan isn't Xorg free).

**Comment by hussamT** [comment] 2017-06-23 15:51
in my case  libEGL_mesa was loaded unconditionally. it seems whatever loader/algorithm here was not working properly because the nvidia file and mesa file are called  50_mesa.json and 10_nvidia.json so logically 10_... is parsed first.
I had to remove 50_mesa... to let gnome-shell use libEGL_nvidia instead.

**Comment by kwizart** [comment] 2017-06-23 15:54
@hussamT
What is your distro and can you report a working eglinfo with your setup ?

**Comment by hussamT** [comment] 2017-06-23 16:00
Arch Linux. I'll look up eglinfo.

**Comment by kwizart** [comment] 2017-07-10 12:26
Tested with 384.47 beta, it's working fine. (eglinfo report using intel when the intel driver is used on a setup where the nvidia driver is installed).

Can we bump libglvnd release , so packagers have an appropriate means to enforce newer libglvnd when using this release ?

Thx

**Comment by kbrenneman** [comment] 2017-07-10 15:15
GLVND was fine, and the current version will still work. This bug was a bug in the NVIDIA driver itself, which is fixed in 384.47. So, you can use the same GLVND version with the rest of 384.47 and it'll still work.

I think Mesa also has the same eglGetPlatformDisplay behavior that a pre-384.47 NVIDIA driver does, in that it'll unconditionally return a non-NULL handle from eglGetPlatformDisplay. But, that wouldn't cause a problem if the driver the NVIDIA driver is listed before Mesa in GLVND's load order.

**Comment by kbrenneman** [comment] 2017-07-10 16:30
From a quick test, it looks like the Mesa behavior is actually correct. I can run EGL programs with Mesa as the vendor library even if the X screen is running with the NVIDIA driver.

**Comment by kbrenneman** [comment] 2017-07-29 14:44
I've confirmed that the underlying bug in the NVIDIA driver is fixed in version 384.59, as well as in 384.47 (which was a beta release).

**Closed by kbrenneman** 2017-07-29 14:44 UTC
